# ansible-playbook -i hosts ./playbooks/0_update.yml --become
# http://docs.ansible.com/ansible/latest/modules/apt_module.html
# https://stackoverflow.com/questions/22107610/shell-script-run-function-from-script-over-ssh

- hosts: production_ubuntu
  become: yes
  become_user: root

  tasks:
    - name: apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 1000

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
