# https://nodesource.com/blog/installing-node-js-tutorial-ubuntu/

#

- hosts: production_ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Download and Set Up the Correct APT Repo
      shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -

    - name: Run Apt-get
      apt:
        name: nodejs
        state: latest

    # - name: install npm
    #   apt:
    #     name: npm
    #     state: latest

    - name: Print Out Node Version
      shell: node -v
      register: version

    - debug: var=version
      # {{ version['stdout'] }}

    # -name: ppa
    #   get_url:
    #     url: https://deb.nodesource.com/setup_8.x
    #     dest: ~/nodesource_setup.sh
