- hosts: remote
  become: yes
  become_user: root


  tasks:
    - name: install nvm
      # shell: curl https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh | bash
      get_url:
        url: https://raw.githubusercontent.com/creationix/nvm/v0.13.1/install.sh
        dest: ~/.nvm
    
    - name: run nvm
      shell: source ~/.bash_profile

    - name: get status
      command: ls
